<?php
$mainurl="Subscribe";
$style="1";
$sendermail="reklama@duschy.biz";
$sendername="Name";
$sendertheme="Подписка";
$senderurl="http://duschy.infobox.ru";
$senderfolder="/sub";
$charset="windows-1251";
$lettype="plain";
$username="Admin";
$password="111";
?>